{'root_assembly': 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)', 'name_assembly': 'ALS.PROJECT.ZONE.XX.00.00.000.iam', 'new_root_assembly': '', 'new_name_assembly': '', 'item': {'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.000.iam': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.000', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.000', 'short_filename': '\\', 'image': 'iam_image.png', 'type_file': '.iam', 'rules': {'Параметры': '\r\n\'Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Длина") = Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Длина") = Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Длина") = Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Длина") = Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "Длина") = Длина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Длина") = Длина\r\n\r\n\'Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Ширина") = Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Ширина") = Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Ширина") = Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Ширина") = Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "Ширина") = Ширина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Ширина") = Ширина\r\n\r\n\'Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Высота") = Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Высота") = Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Высота") = Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Высота") = Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "Высота") = Высота\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Высота") = Высота\r\n\r\n\'УШП - угол наклона по ширине правый \r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "УШП") = УШП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "УШП") = УШП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "УШП") = УШП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "УШП") = УШП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "УШП") = УШП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "УШП") = УШП\r\n\r\n\'УШЛ - угол наклона по ширине левый\r\nIf Смещение = 0 Then\r\n\tУШЛ = УШП\r\nEnd If\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "УШЛ") = УШЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "УШЛ") = УШЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "УШЛ") = УШЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "УШЛ") = УШЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "УШЛ") = УШЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "УШЛ") = УШЛ\r\n\r\n\'УД - угол наклона по длине\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "УД") = УД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "УД") = УД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "УД") = УД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "УД") = УД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "УД") = УД\r\n\r\n\'Толщина - толщина основания и стенок\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Толщина") = Толщина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Толщина") = Толщина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Толщина") = Толщина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "Толщина") = Толщина\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Толщина") = Толщина\r\n\r\n\'Смещение - смещение патрубка в бок\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Смещение") = Смещение\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Смещение") = Смещение\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Смещение") = Смещение\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Смещение") = Смещение\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "Смещение") = Смещение\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Смещение") = Смещение\r\n\r\n\r\n\'Материал\r\nFor Each subdoc in ThisApplication.ActiveDocument.AllReferencedDocuments\r\n\tIf InStr(subdoc.DisplayName, "Соед") = 0 Then\r\n\t\tsubdoc.ComponentDefinition.Material.Name = Материал\r\n\tEnd If\r\nNext subdoc\r\n\r\n\r\n', 'Исполнение': '\'DN = 65\' удаленный параметр\r\n\r\nIf Патрубок = "Нижний" Then\r\n\tConstraint.IsActive("Совмещение:6") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Выдавливание9") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание3") = 0\r\n\tConstraint.IsActive("Совмещение:5") = 0\r\n\r\n\tConstraint.IsActive("Совмещение:9") = 1\r\n\t\'Constraint.IsActive("Совмещение:2") = 1\r\n\tConstraint.IsActive("Угол:3") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Выдавливание10") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Сопряжение10") = 1\r\n\t\r\nElseIf Патрубок = "Боковой" Then\r\n\tConstraint.IsActive("Совмещение:6") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Выдавливание9") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание3") = 1\r\n\tConstraint.IsActive("Совмещение:5") = 1\r\n\r\n\tConstraint.IsActive("Совмещение:9") = 0\r\n\t\'Constraint.IsActive("Совмещение:2") = 0\r\n\tConstraint.IsActive("Угол:3") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Выдавливание10") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Сопряжение10") = 0\r\nEnd If\r\n\r\nSelect DN\r\nCase "DN10"\r\n\tOD = 13\r\n\tТП = 1.5\r\nCase "DN15"\r\n\tOD = 19\r\n\tТП = 1.5\r\nCase "DN20"\r\n\tOD = 23\r\n\tТП = 1.5\r\nCase "DN25"\r\n\tOD = 29\r\n\tТП = 1.5\r\nCase "DN32"\r\n\tOD = 35\r\n\tТП = 1.5\r\nCase "DN40"\r\n\tOD = 41\r\n\tТП = 1.5\r\nCase "DN50"\r\n\tOD = 53\r\n\tТП = 1.5\r\nCase "DN65"\r\n\tOD = 70\r\n\tТП = 2\r\nCase "DN80"\r\n\tOD = 85\r\n\tТП = 2\r\nCase "DN100"\r\n\tOD = 104\r\n\tТП = 2\r\nCase "ISO_1\'\'"\r\n\tOD = 25\r\n\tТП = 1.2\r\nCase "ISO_1,5\'\'"\r\n\tOD = 38\r\n\tТП = 1.2\r\nCase "ISO_2\'\'"\r\n\tOD = 51\r\n\tТП = 1.2\r\nCase "ISO_2,5\'\'"\r\n\tOD = 63.5\r\n\tТП = 1.6\r\nCase "ISO_3\'\'"\r\n\tOD = 76.1\r\n\tТП = 1.6\r\nCase "ISO_4\'\'"\r\n\tOD = 101.6\r\n\tТП = 2\r\nEnd Select\r\n\r\n\'OD\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "OD") = OD\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "OD") = OD\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "OD") = OD\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "OD") = OD\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "OD") = OD\r\n\r\n\'ТП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "ТП") = ТП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "ТП") = ТП\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "ТП") = ТП\r\n\r\n\'ДПН - длина нижнего патрубка\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "ДПН") = ДПН\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "ДПН") = ДПН\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "ДПН") = ДПН\r\n\r\n\'ДПВ - длина патрубка внешняя \r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "ДПВ") = ДПВ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "ДПВ") = ДПВ\r\n\r\n\'НПР - растояние отверстия ниженго патрубка до передний стенки \r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "НПР") = НПР\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "НПР") = НПР\r\n\r\n\'k_ - Высота нижнего патрубка\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "k_") = k_\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "k_") = k_\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка", "k_") = k_\r\n\r\n\'Наименования для спецификации\r\ndes = ""\r\ntc = ""\r\nIf InStr(DN, "DN") Then\r\n\tdes = "Труба DIN11850"\r\n\ttc = DN & "(" & OD & "x" & ТП & ")"\r\nElse\r\n\tdes = "Труба ISO2037" \r\n\ttc = Split(DN, "_")(1) & "(" & OD & "x" & ТП & ")"\r\nEnd If\r\n\r\niProperties.Value("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Custom", "Технические характеристики") = tc\r\niProperties.Value("ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой", "Project", "Description") = des\r\n\r\niProperties.Value("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Custom", "Технические характеристики") = tc\r\niProperties.Value("ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний", "Project", "Description") = des\r\n\r\n', 'Ручки': 'Select Case Сторона1\r\nCase 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:1") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:2") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:3") = 0\r\nCase 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:1") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:2") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:3") = 0\r\nCase 2\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:1") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:2") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:3") = 1\r\nCase 3\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:1") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:2") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:3") = 1\r\nEnd Select\r\n\r\nSelect Case Сторона2\r\nCase 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:5") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:6") = 0\r\nCase 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:5") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:5") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:6") = 0\r\nCase 2\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:5") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:6") = 1\r\nCase 3\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:5") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:6") = 1\r\nEnd Select\r\n\r\nSelect Case Сторона3\r\nCase 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:7") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:8") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:9") = 0\r\nCase 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:7") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:8") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:9") = 0\r\nCase 2\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:7") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:8") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:9") = 1\r\nCase 3\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:7") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:8") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:9") = 1\r\nEnd Select\r\n\r\nSelect Case Сторона4\r\nCase 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:10") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:11") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:12") = 0\r\nCase 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:10") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:11") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:12") = 0\r\nCase 2\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:10") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:11") = 0\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:12") = 1\r\nCase 3\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:10") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:11") = 1\r\n\tComponent.IsActive("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:12") = 1\r\nEnd Select\r\n\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4", "РД") = РД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4", "РДЛ") = РДЛ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.007 Ручка:4", "РШ") = РШ\r\n', 'Соединение': '_dn = DN\r\n\r\nIf InStr(DN, "ISO") <> 0 Then\r\n\t_dn = Split(DN, "_")(1)\r\nEnd If \r\n\r\nFor Each com in ThisApplication.ActiveDocument.ComponentDefinition.Occurrences\r\n\tcom_name = com.Name\r\n\tIf InStr(com_name, "Соед") <> 0 Then\r\n\t\tIf Патрубок = "Боковой" Then\r\n\t\t\tIf InStr(com.Name, ":1") <> 0 Then\r\n\t\t\t\tComponent.IsActive(com.Name) = 1\r\n\t\t\tElse\r\n\t\t\t\tComponent.IsActive(com.Name) = 0\r\n\t\t\tEnd If\r\n\t\tElse\r\n\t\t\tIf InStr(com.Name, ":1") <> 0 Then\r\n\t\t\t\tComponent.IsActive(com.Name) = 0\r\n\t\t\tElse\r\n\t\t\t\tComponent.IsActive(com.Name) = 1\r\n\t\t\tEnd If\r\n\t\tEnd If\r\n\t\t\r\n\t\tIf Материал = "AISI304" Then\r\n\t\t\tmat = "EPDM"\r\n\t\tElse \r\n\t\t\tmat = "PTFE"\r\n\t\tEnd If\r\n\tiPart.ChangeRow(com_name, "Соединение длин., DIN EN 10357, " & _dn & "(" & mat &"), " & Материал & "L")\r\n\r\n\t\r\n\t\r\n\tEnd If\r\nNext com \r\n\r\n\r\n\r\n', 'Отгибка': '\'ФУ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "ФУ") = ФУ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "ФУ") = ФУ\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "ФУ") = ФУ\r\n\r\n\'ФД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "ФД") = ФД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "ФД") = ФД\r\nParameter("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "ФД") = ФД\r\n\r\nIf Отгибка = "Нет" Then \r\n\tФУ = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска1") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска2") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска3") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска4") = 0\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание4") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Сопряжение5") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание6") = 0\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание4") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Сопряжение5") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание6") = 0\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание7") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание7") = 1\r\nElse\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска1") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска2") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска3") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка", "Фаска4") = 1\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание4") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Сопряжение5") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание6") = 1\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание4") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Сопряжение5") = 1\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание6") = 1\r\n\t\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка", "Выдавливание7") = 0\r\n\tFeature.IsActive("ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка", "Выдавливание7") = 0\r\nEnd If'}, 'item': {'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.001 Основа лотка.ipt', 'image': 'ipt_image.png', 'rules': {'Размеры развёртки': 'iProperties.Value("Custom", "Технические характеристики") = Толщина & "x" & Floor(SheetMetal.FlatExtentsLength) & "x" & Floor(SheetMetal.FlatExtentsWidth)\r\n\r\n\r\n\r\n'}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.002 Передняя стенка.ipt', 'image': 'ipt_image.png', 'rules': {'Размеры развёртки': 'iProperties.Value("Custom", "Технические характеристики") = Толщина & "x" & Floor(SheetMetal.FlatExtentsLength) & "x" & Floor(SheetMetal.FlatExtentsWidth)\r\n\r\n'}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.003 Задняя стенка.ipt', 'image': 'ipt_image.png', 'rules': {'Размеры развёртки': 'iProperties.Value("Custom", "Технические характеристики") = Толщина & "x" & Floor(SheetMetal.FlatExtentsLength) & "x" & Floor(SheetMetal.FlatExtentsWidth)\r\n\r\n'}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.004 Патрубок боковой.ipt', 'image': 'ipt_image.png', 'rules': {}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.005 Заглушка.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.005 Заглушка патрубка', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.005 Заглушка.ipt', 'image': 'ipt_image.png', 'rules': {'Размеры развёртки': 'iProperties.Value("Custom", "Технические характеристики") = Толщина & "x" & Floor(SheetMetal.FlatExtentsLength) & "x" & Floor(SheetMetal.FlatExtentsWidth)\r\n\r\n'}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.006 Патрубок нижний.ipt', 'image': 'ipt_image.png', 'rules': {}, 'type_file': '.ipt', 'item': {}}, 'C:\\tmp\\temp assembly\\v1.6 (copy at 19-10-2025$14-35-39)\\ALS.PROJECT.ZONE.XX.00.00.007 Ручка.ipt': {'component_name': 'ALS.PROJECT.ZONE.XX.00.00.007 Ручка', 'display_name': 'ALS.PROJECT.ZONE.XX.00.00.007 Ручка', 'short_filename': '\\ALS.PROJECT.ZONE.XX.00.00.007 Ручка.ipt', 'image': 'ipt_image.png', 'rules': {}, 'type_file': '.ipt', 'item': {}}}}}}